### ISSUE TITLE
Django 2.2 requires SQLite 3.8.3 or later on CentOS 7

### ISSUE THREAD

**Issue by Quoding** [ubccr/coldfront#207]
It seems that the Django version required by ColdFront isn't in line with the present version of SQLite on CentOS 7. 

The latest SQLite version yum (with epel enabled) gives is 3.7.17, which is lower than the minimum required by Django 2.2.

It seems that the plausible workaround for now is to install SQLite from source.

This is the output during the initial setup:
```Traceback (most recent call last):                                                                                                                                                   [294/524]
  File "/centos/coldfront_app/venv/bin/coldfront", line 11, in <module>                                                                                                                       
    load_entry_point('coldfront', 'console_scripts', 'coldfront')()                                                                                                                           
  File "/centos/coldfront_app/coldfront/coldfront/__init__.py", line 11, in manage                                                                                                            
    execute_from_command_line(sys.argv)                                                                                                                                                       
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line                                                  
    utility.execute()                                                                                                                                                                         
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute                                                                    
    django.setup()                                                                                                                                                                            
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup                                                                                       
    apps.populate(settings.INSTALLED_APPS)                                                                                                                                                    
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)                                     
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module                
    return _bootstrap._gcd_import(name[level:], package, level)                                
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                               
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                            
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                   
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                            
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                      
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                 
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager                
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))                                  
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())             
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)                                        
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)                                             
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module                
    return _bootstrap._gcd_import(name[level:], package, level)                                
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/centos/coldfront_app/venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17). ```

**Comment by stanier** [comment]
According to [this ticket on Django's issue tracker](https://code.djangoproject.com/ticket/30313), the Django team has filed this as a Won't Fix.  Unfortunately this brings the minimum OS spec to Centos 8 or it's RHEL equivalent.

I've tested a local deployment against Centos 8 with no issues, but the documentation may need to be updated to reflect this as 7.7 does not have backports for SQLite 3.8.3 afaik

**Comment by mkzia** [comment]
@Quoding @stanier Have you guys tried installing SQLite from source? That worked for us in the development environment. For production, we suggest that you use MySQL.

**Comment by Quoding** [comment]
Alright. My primary thought was indeed to update the documentation. I'll close this issue, fork and PR.

**Comment by mkzia** [comment]
Do you also need to export LD library path after install SQLite from source, `export LD_LIBRARY_PATH=/usr/local/lib`? I remember doing something like that.
